security:
    encoders:
        Aseagle\Bundle\UserBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
#        ROLE_MANAGER:     ROLE_USER
#        ROLE_ADMIN:       [ROLE_MANAGER, ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        frontend:
            entity: { class: "AseagleUserBundle:User", property: email }
        backend:
            entity: { class: "AseagleUserBundle:User", property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        demo_login:
            pattern:  ^/demo/secured/login$
            security: false

        member_area:
            pattern:    ^/admin/
            form_login:
                check_path: /admin/login_check
                login_path: /admin/login
                default_target_path: /admin
                use_referer: true
                use_forward:    false
                failure_path:   null              
            logout:
                path:   /admin/logout
                target: /admin/login
            anonymous: true
            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER
            provider: backend
            
        front_area:
            pattern:    ^/(?!(admin)).*$
            form_login:
                check_path: /login_check
                login_path: /dang-nhap.html
                default_target_path: /
                use_referer: true
                use_forward:    false
                failure_path:   null              
            logout:
                path:   /dang-xuat.html
                target: /dang-nhap.html
            anonymous: true
            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER
            provider: frontend

    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/admin, roles: [ROLE_ADMIN, ROLE_MANAGER, ROLE_BACKEND]}
        
    acl:
        connection: default
        